project:
  type: book

book:
  title: "Mini-hidroelectrica EH 26289"
  author: "Norah Jones"
  date: "17/3/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



